///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace clc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the clcRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
    [RepositoryFolder("c5c479d3-2633-457f-9cb5-7706cbe54bb8")]
    public partial class clcRepository : RepoGenBaseFolder
    {
        static clcRepository instance = new clcRepository();
        clcRepositoryFolders.КалькуляторAppFolder _калькулятор;

        /// <summary>
        /// Gets the singleton class instance representing the clcRepository element repository.
        /// </summary>
        [RepositoryFolder("c5c479d3-2633-457f-9cb5-7706cbe54bb8")]
        public static clcRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public clcRepository() 
            : base("clcRepository", "/", null, 0, false, "c5c479d3-2633-457f-9cb5-7706cbe54bb8", ".\\RepositoryImages\\clcRepositoryc5c479d3.rximgres")
        {
            _калькулятор = new clcRepositoryFolders.КалькуляторAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c5c479d3-2633-457f-9cb5-7706cbe54bb8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Калькулятор folder.
        /// </summary>
        [RepositoryFolder("49e1f289-fd83-4cd4-aa72-49bcf992aa11")]
        public virtual clcRepositoryFolders.КалькуляторAppFolder Калькулятор
        {
            get { return _калькулятор; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
    public partial class clcRepositoryFolders
    {
        /// <summary>
        /// The КалькуляторAppFolder folder.
        /// </summary>
        [RepositoryFolder("49e1f289-fd83-4cd4-aa72-49bcf992aa11")]
        public partial class КалькуляторAppFolder : RepoGenBaseFolder
        {
            clcRepositoryFolders.CalcFolder _calc;

            /// <summary>
            /// Creates a new Калькулятор  folder.
            /// </summary>
            public КалькуляторAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Калькулятор", "/form[@title='Калькулятор']", parentFolder, 30000, null, true, "49e1f289-fd83-4cd4-aa72-49bcf992aa11", "")
            {
                _calc = new clcRepositoryFolders.CalcFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49e1f289-fd83-4cd4-aa72-49bcf992aa11")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49e1f289-fd83-4cd4-aa72-49bcf992aa11")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Calc folder.
            /// </summary>
            [RepositoryFolder("46cb405a-9208-4feb-ae84-713166b5810c")]
            public virtual clcRepositoryFolders.CalcFolder Calc
            {
                get { return _calc; }
            }
        }

        /// <summary>
        /// The CalcFolder folder.
        /// </summary>
        [RepositoryFolder("46cb405a-9208-4feb-ae84-713166b5810c")]
        public partial class CalcFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button2Info;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _button1Info;

            /// <summary>
            /// Creates a new Calc  folder.
            /// </summary>
            public CalcFolder(RepoGenBaseFolder parentFolder) :
                    base("Calc", "?/?/container[@instance='1']", parentFolder, 30000, null, false, "46cb405a-9208-4feb-ae84-713166b5810c", "")
            {
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='121']", 30000, null, "d907a940-0cc1-450d-a223-ba4a07d0dcd2");
                _buttonInfo = new RepoItemInfo(this, "Button", "button[@controlid='131']", 30000, null, "73383b56-bf8e-423f-85bb-f62fb633e400");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='93']", 30000, null, "b53c79b9-ab74-422f-9aa1-b9cfe402309d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("46cb405a-9208-4feb-ae84-713166b5810c")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("46cb405a-9208-4feb-ae84-713166b5810c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("d907a940-0cc1-450d-a223-ba4a07d0dcd2")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("d907a940-0cc1-450d-a223-ba4a07d0dcd2")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("73383b56-bf8e-423f-85bb-f62fb633e400")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("73383b56-bf8e-423f-85bb-f62fb633e400")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("b53c79b9-ab74-422f-9aa1-b9cfe402309d")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("b53c79b9-ab74-422f-9aa1-b9cfe402309d")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}