///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRecBinAll
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("a5c68eab-31e4-4d33-94d8-021166ca398b", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRecBinAllRepository repository.
        /// </summary>
        public static TestRecBinAllRepository repo = TestRecBinAllRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List11.List1' at 630;395.", repo.Explorer.List11.List1Info, new RecordItemIndex(0));
            repo.Explorer.List11.List1.Click(System.Windows.Forms.MouseButtons.Right, "630;395");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Создать' at 75;18.", repo.Explorer1.СоздатьInfo, new RecordItemIndex(1));
            repo.Explorer1.Создать.Click("75;18");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer2.ТекстовыйДокумент' at 69;9.", repo.Explorer2.ТекстовыйДокументInfo, new RecordItemIndex(2));
            repo.Explorer2.ТекстовыйДокумент.Click("69;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.List11.List1' at 834;466.", repo.Explorer.List11.List1Info, new RecordItemIndex(3));
            repo.Explorer.List11.List1.Click("834;466");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List11.НовыйТекстовыйДокумент' at 24;47.", repo.Explorer.List11.НовыйТекстовыйДокументInfo, new RecordItemIndex(4));
            repo.Explorer.List11.НовыйТекстовыйДокумент.Click(System.Windows.Forms.MouseButtons.Right, "24;47");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Удалить' at 62;4.", repo.Explorer1.УдалитьInfo, new RecordItemIndex(5));
            repo.Explorer1.Удалить.Click("62;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'УдалитьФайл.ButtonДа' at 36;16.", repo.УдалитьФайл.ButtonДаInfo, new RecordItemIndex(6));
            repo.УдалитьФайл.ButtonДа.Click("36;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Explorer.List11.Корзина' at 56;43.", repo.Explorer.List11.КорзинаInfo, new RecordItemIndex(7));
            repo.Explorer.List11.Корзина.DoubleClick("56;43");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Корзина.Button47C4C3B2499845CEA2C035BD8A96C' at 57;15.", repo.Корзина.Button47C4C3B2499845CEA2C035BD8A96CInfo, new RecordItemIndex(8));
            repo.Корзина.Button47C4C3B2499845CEA2C035BD8A96C.Click("57;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'УдалитьФайл.ButtonДа' at 46;16.", repo.УдалитьФайл.ButtonДаInfo, new RecordItemIndex(9));
            repo.УдалитьФайл.ButtonДа.Click("46;16");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'Корзина.ListItem0'.", repo.Корзина.ListItem0Info, new RecordItemIndex(10));
            Validate.NotExists(repo.Корзина.ListItem0Info);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
