///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestRecBinAll
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRecBinAllRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
    [RepositoryFolder("473dc27c-ad5d-434e-aacb-adf0b343248e")]
    public partial class TestRecBinAllRepository : RepoGenBaseFolder
    {
        static TestRecBinAllRepository instance = new TestRecBinAllRepository();
        TestRecBinAllRepositoryFolders.ExplorerAppFolder _explorer;
        TestRecBinAllRepositoryFolders.Explorer1AppFolder _explorer1;
        TestRecBinAllRepositoryFolders.Explorer2AppFolder _explorer2;
        TestRecBinAllRepositoryFolders.УдалитьФайлAppFolder _удалитьфайл;
        TestRecBinAllRepositoryFolders.КорзинаAppFolder _корзина;

        /// <summary>
        /// Gets the singleton class instance representing the TestRecBinAllRepository element repository.
        /// </summary>
        [RepositoryFolder("473dc27c-ad5d-434e-aacb-adf0b343248e")]
        public static TestRecBinAllRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRecBinAllRepository() 
            : base("TestRecBinAllRepository", "/", null, 0, false, "473dc27c-ad5d-434e-aacb-adf0b343248e", ".\\RepositoryImages\\TestRecBinAllRepository473dc27c.rximgres")
        {
            _explorer = new TestRecBinAllRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new TestRecBinAllRepositoryFolders.Explorer1AppFolder(this);
            _explorer2 = new TestRecBinAllRepositoryFolders.Explorer2AppFolder(this);
            _удалитьфайл = new TestRecBinAllRepositoryFolders.УдалитьФайлAppFolder(this);
            _корзина = new TestRecBinAllRepositoryFolders.КорзинаAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("473dc27c-ad5d-434e-aacb-adf0b343248e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("7cee25f4-68a3-4f7a-91f7-5535a27d6e4a")]
        public virtual TestRecBinAllRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("71078cc4-9d07-41f4-bc40-db228950b602")]
        public virtual TestRecBinAllRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The Explorer2 folder.
        /// </summary>
        [RepositoryFolder("55d10cd1-ad03-404e-92b6-afcacbbdf084")]
        public virtual TestRecBinAllRepositoryFolders.Explorer2AppFolder Explorer2
        {
            get { return _explorer2; }
        }

        /// <summary>
        /// The УдалитьФайл folder.
        /// </summary>
        [RepositoryFolder("f4eb98e8-664d-4dc2-b68b-98b2bc500142")]
        public virtual TestRecBinAllRepositoryFolders.УдалитьФайлAppFolder УдалитьФайл
        {
            get { return _удалитьфайл; }
        }

        /// <summary>
        /// The Корзина folder.
        /// </summary>
        [RepositoryFolder("fc2d8f05-2804-4a58-84d4-05031aa0cc40")]
        public virtual TestRecBinAllRepositoryFolders.КорзинаAppFolder Корзина
        {
            get { return _корзина; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.0")]
    public partial class TestRecBinAllRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("7cee25f4-68a3-4f7a-91f7-5535a27d6e4a")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            TestRecBinAllRepositoryFolders.List11Folder _list11;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "7cee25f4-68a3-4f7a-91f7-5535a27d6e4a", "")
            {
                _list11 = new TestRecBinAllRepositoryFolders.List11Folder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7cee25f4-68a3-4f7a-91f7-5535a27d6e4a")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7cee25f4-68a3-4f7a-91f7-5535a27d6e4a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List11 folder.
            /// </summary>
            [RepositoryFolder("a3219a73-a9d2-44be-9884-03baa71861a7")]
            public virtual TestRecBinAllRepositoryFolders.List11Folder List11
            {
                get { return _list11; }
            }
        }

        /// <summary>
        /// The List11Folder folder.
        /// </summary>
        [RepositoryFolder("a3219a73-a9d2-44be-9884-03baa71861a7")]
        public partial class List11Folder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;
            RepoItemInfo _корзинаInfo;
            RepoItemInfo _новыйтекстовыйдокументInfo;

            /// <summary>
            /// Creates a new List11  folder.
            /// </summary>
            public List11Folder(RepoGenBaseFolder parentFolder) :
                    base("List11", "?/?/list[@controlid='1']", parentFolder, 30000, null, false, "a3219a73-a9d2-44be-9884-03baa71861a7", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "", 30000, null, "9c373d38-e4c6-4924-a94c-0074f652aa06");
                _корзинаInfo = new RepoItemInfo(this, "Корзина", "listitem[@text='Корзина']", 30000, null, "577b8aef-55fa-4aad-b211-3f65f0947d3a");
                _новыйтекстовыйдокументInfo = new RepoItemInfo(this, "НовыйТекстовыйДокумент", "listitem[@text='Новый текстовый документ']", 30000, null, "571ead8b-4d55-4169-851b-8242e0c4b852");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a3219a73-a9d2-44be-9884-03baa71861a7")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a3219a73-a9d2-44be-9884-03baa71861a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("9c373d38-e4c6-4924-a94c-0074f652aa06")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("9c373d38-e4c6-4924-a94c-0074f652aa06")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }

            /// <summary>
            /// The Корзина item.
            /// </summary>
            [RepositoryItem("577b8aef-55fa-4aad-b211-3f65f0947d3a")]
            public virtual Ranorex.ListItem Корзина
            {
                get
                {
                    return _корзинаInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Корзина item info.
            /// </summary>
            [RepositoryItemInfo("577b8aef-55fa-4aad-b211-3f65f0947d3a")]
            public virtual RepoItemInfo КорзинаInfo
            {
                get
                {
                    return _корзинаInfo;
                }
            }

            /// <summary>
            /// The НовыйТекстовыйДокумент item.
            /// </summary>
            [RepositoryItem("571ead8b-4d55-4169-851b-8242e0c4b852")]
            public virtual Ranorex.ListItem НовыйТекстовыйДокумент
            {
                get
                {
                    return _новыйтекстовыйдокументInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The НовыйТекстовыйДокумент item info.
            /// </summary>
            [RepositoryItemInfo("571ead8b-4d55-4169-851b-8242e0c4b852")]
            public virtual RepoItemInfo НовыйТекстовыйДокументInfo
            {
                get
                {
                    return _новыйтекстовыйдокументInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("71078cc4-9d07-41f4-bc40-db228950b602")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _создатьInfo;
            RepoItemInfo _удалитьInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/contextmenu[@class='#32768' and @instance='0']", parentFolder, 30000, null, true, "71078cc4-9d07-41f4-bc40-db228950b602", "")
            {
                _создатьInfo = new RepoItemInfo(this, "Создать", "?/?/menuitem[@accessiblename='Создать']", 30000, null, "901e7968-dde7-446a-ae79-fe29fcf5a733");
                _удалитьInfo = new RepoItemInfo(this, "Удалить", "?/?/menuitem[@accessiblename='Удалить']", 30000, null, "5541cadb-f975-4af7-b539-be36927467db");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71078cc4-9d07-41f4-bc40-db228950b602")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71078cc4-9d07-41f4-bc40-db228950b602")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Создать item.
            /// </summary>
            [RepositoryItem("901e7968-dde7-446a-ae79-fe29fcf5a733")]
            public virtual Ranorex.MenuItem Создать
            {
                get
                {
                    return _создатьInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Создать item info.
            /// </summary>
            [RepositoryItemInfo("901e7968-dde7-446a-ae79-fe29fcf5a733")]
            public virtual RepoItemInfo СоздатьInfo
            {
                get
                {
                    return _создатьInfo;
                }
            }

            /// <summary>
            /// The Удалить item.
            /// </summary>
            [RepositoryItem("5541cadb-f975-4af7-b539-be36927467db")]
            public virtual Ranorex.MenuItem Удалить
            {
                get
                {
                    return _удалитьInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Удалить item info.
            /// </summary>
            [RepositoryItemInfo("5541cadb-f975-4af7-b539-be36927467db")]
            public virtual RepoItemInfo УдалитьInfo
            {
                get
                {
                    return _удалитьInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer2AppFolder folder.
        /// </summary>
        [RepositoryFolder("55d10cd1-ad03-404e-92b6-afcacbbdf084")]
        public partial class Explorer2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _текстовыйдокументInfo;

            /// <summary>
            /// Creates a new Explorer2  folder.
            /// </summary>
            public Explorer2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer2", "/contextmenu[@class='#32768' and @instance='1']", parentFolder, 30000, null, true, "55d10cd1-ad03-404e-92b6-afcacbbdf084", "")
            {
                _текстовыйдокументInfo = new RepoItemInfo(this, "ТекстовыйДокумент", "?/?/menuitem[@accessiblename='Текстовый документ']", 30000, null, "c4b11f03-7567-47e5-8e46-8353722ca020");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55d10cd1-ad03-404e-92b6-afcacbbdf084")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55d10cd1-ad03-404e-92b6-afcacbbdf084")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ТекстовыйДокумент item.
            /// </summary>
            [RepositoryItem("c4b11f03-7567-47e5-8e46-8353722ca020")]
            public virtual Ranorex.MenuItem ТекстовыйДокумент
            {
                get
                {
                    return _текстовыйдокументInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ТекстовыйДокумент item info.
            /// </summary>
            [RepositoryItemInfo("c4b11f03-7567-47e5-8e46-8353722ca020")]
            public virtual RepoItemInfo ТекстовыйДокументInfo
            {
                get
                {
                    return _текстовыйдокументInfo;
                }
            }
        }

        /// <summary>
        /// The УдалитьФайлAppFolder folder.
        /// </summary>
        [RepositoryFolder("f4eb98e8-664d-4dc2-b68b-98b2bc500142")]
        public partial class УдалитьФайлAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonдаInfo;

            /// <summary>
            /// Creates a new УдалитьФайл  folder.
            /// </summary>
            public УдалитьФайлAppFolder(RepoGenBaseFolder parentFolder) :
                    base("УдалитьФайл", "/form[@title='Удалить файл']", parentFolder, 30000, null, true, "f4eb98e8-664d-4dc2-b68b-98b2bc500142", "")
            {
                _buttonдаInfo = new RepoItemInfo(this, "ButtonДа", "button[@text='Д&а']", 30000, null, "ac84169c-50b7-4c65-8427-0c5f169e1f98");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f4eb98e8-664d-4dc2-b68b-98b2bc500142")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f4eb98e8-664d-4dc2-b68b-98b2bc500142")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonДа item.
            /// </summary>
            [RepositoryItem("ac84169c-50b7-4c65-8427-0c5f169e1f98")]
            public virtual Ranorex.Button ButtonДа
            {
                get
                {
                    return _buttonдаInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonДа item info.
            /// </summary>
            [RepositoryItemInfo("ac84169c-50b7-4c65-8427-0c5f169e1f98")]
            public virtual RepoItemInfo ButtonДаInfo
            {
                get
                {
                    return _buttonдаInfo;
                }
            }
        }

        /// <summary>
        /// The КорзинаAppFolder folder.
        /// </summary>
        [RepositoryFolder("fc2d8f05-2804-4a58-84d4-05031aa0cc40")]
        public partial class КорзинаAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button47c4c3b2499845cea2c035bd8a96cInfo;
            RepoItemInfo _listitem0Info;

            /// <summary>
            /// Creates a new Корзина  folder.
            /// </summary>
            public КорзинаAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Корзина", "/form[@title='Корзина']", parentFolder, 30000, null, true, "fc2d8f05-2804-4a58-84d4-05031aa0cc40", "")
            {
                _button47c4c3b2499845cea2c035bd8a96cInfo = new RepoItemInfo(this, "Button47C4C3B2499845CEA2C035BD8A96C", "element[@class='ShellTabWindowClass']//toolbar[@automationid='FolderBandModuleInner']/button[@automationid='{47C4C3B2-4998-45CE-A2C0-35BD8A96C726}']", 30000, null, "dce74941-6676-44ec-bd57-5d345eb60cd3");
                _listitem0Info = new RepoItemInfo(this, "ListItem0", "element[@class='ShellTabWindowClass']//element[@instance='1']/container[@caption='ShellView']/?/?/listitem[@automationid='0']", 1000, null, "fd84eb89-ae44-4641-8a3d-1c691d7a230b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fc2d8f05-2804-4a58-84d4-05031aa0cc40")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc2d8f05-2804-4a58-84d4-05031aa0cc40")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button47C4C3B2499845CEA2C035BD8A96C item.
            /// </summary>
            [RepositoryItem("dce74941-6676-44ec-bd57-5d345eb60cd3")]
            public virtual Ranorex.Button Button47C4C3B2499845CEA2C035BD8A96C
            {
                get
                {
                    return _button47c4c3b2499845cea2c035bd8a96cInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button47C4C3B2499845CEA2C035BD8A96C item info.
            /// </summary>
            [RepositoryItemInfo("dce74941-6676-44ec-bd57-5d345eb60cd3")]
            public virtual RepoItemInfo Button47C4C3B2499845CEA2C035BD8A96CInfo
            {
                get
                {
                    return _button47c4c3b2499845cea2c035bd8a96cInfo;
                }
            }

            /// <summary>
            /// The ListItem0 item.
            /// </summary>
            [RepositoryItem("fd84eb89-ae44-4641-8a3d-1c691d7a230b")]
            public virtual Ranorex.ListItem ListItem0
            {
                get
                {
                    return _listitem0Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem0 item info.
            /// </summary>
            [RepositoryItemInfo("fd84eb89-ae44-4641-8a3d-1c691d7a230b")]
            public virtual RepoItemInfo ListItem0Info
            {
                get
                {
                    return _listitem0Info;
                }
            }
        }

    }
#pragma warning restore 0436
}